### ISSUE TITLE
Issue installing geobeam on GCP CloudShell

### ISSUE THREAD

**Issue by hashkanna** [GoogleCloudPlatform/dataflow-geobeam#23]
Seeing the below issue while installing geobeam on GCP Cloud Shell.
```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-07s73wh5/orjson/
```

Version of Python used from venv is 3.7.3
```
(env) --@cloudshell:~ $ python
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Detailed error message
```
Collecting orjson<4.0; python_version >= "3.6" (from apache-beam[gcp]>=2.27.0->geobeam)
  Using cached https://files.pythonhosted.org/packages/75/cd/eac8908d0b4a4b08067bc68c04e52d7601b0ed86bf2a6a3264c46dd51a84/orjson-3.6.3.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-07s73wh5/orjson/setup.py'
```

**Comment by hashkanna** [comment]
Resolved it by upgrading pip

```
python -m pip install --upgrade pip

Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.2.4
```
